/*
 * Copyright 2019-2023 IDsec Solutions AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.idsec.signservice.integration.certificate;

import java.io.Serial;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

import lombok.Builder;
import lombok.Singular;
import lombok.ToString;
import se.idsec.signservice.integration.ApiVersion;
import se.idsec.signservice.integration.core.Extensible;
import se.idsec.signservice.integration.core.Extension;
import se.idsec.signservice.integration.core.ObjectBuilder;

/**
 * When sending a SignRequest, a sign requester specifies a set of requirements for the signature certificate that is
 * generated by the sign service. This class represents these requirements.
 *
 * @author Martin Lindström (martin@idsec.se)
 * @author Stefan Santesson (stefan@idsec.se)
 */
@ToString
@Builder(toBuilder = true)
@JsonInclude(Include.NON_NULL)
public class SigningCertificateRequirements implements Extensible {

  /** For serializing. */
  @Serial
  private static final long serialVersionUID = ApiVersion.SERIAL_VERSION_UID;

  /** The requested certificate type. */
  private CertificateType certificateType;

  /**
   * Defines mappings between the signer's authentication attributes and attributes that are to be placed in the issued
   * signature certificate.
   */
  @Singular
  private List<CertificateAttributeMapping> attributeMappings;

  /** Extensions for the object. */
  private Extension extension;

  /**
   * Default constructor.
   */
  public SigningCertificateRequirements() {
  }

  /**
   * Constructor.
   *
   * @param certificateType the requested certificate type
   * @param attributeMappings mappings between the signer's authentication attributes and attributes that are to be
   *          placed in the issued signature certificate
   * @param extension extensions for the object
   */
  public SigningCertificateRequirements(final CertificateType certificateType,
      final List<CertificateAttributeMapping> attributeMappings, final Extension extension) {
    this.certificateType = certificateType;
    this.attributeMappings = attributeMappings;
    this.extension = extension;
  }

  /**
   * Gets the requested certificate type.
   *
   * @return the requested certificate type
   */
  public CertificateType getCertificateType() {
    return this.certificateType;
  }

  /**
   * Assigns the requested certificate type.
   *
   * @param certificateType requested certificate type
   */
  public void setCertificateType(final CertificateType certificateType) {
    this.certificateType = certificateType;
  }

  /**
   * Gets the mappings between the signer's authentication attributes and attributes that are to be placed in the issued
   * signature certificate.
   *
   * @return a list of mapping directives of how to map from user/signer attributes to signature certificate attributes
   */
  public List<CertificateAttributeMapping> getAttributeMappings() {
    return this.attributeMappings;
  }

  /**
   * Assigns the mappings between the signer's authentication attributes and attributes that are to be placed in the
   * issued signature certificate.
   *
   * @param attributeMappings a list of mapping directives of how to map from user/signer attributes to signature
   *          certificate attributes
   */
  public void setAttributeMappings(final List<CertificateAttributeMapping> attributeMappings) {
    this.attributeMappings = attributeMappings;
  }

  /** {@inheritDoc} */
  @Override
  public Extension getExtension() {
    return this.extension;
  }

  /** {@inheritDoc} */
  @Override
  public void setExtension(final Extension extension) {
    this.extension = extension;
  }

  /**
   * Builder for {@code SigningCertificateRequirements} objects
   */
  public static class SigningCertificateRequirementsBuilder implements ObjectBuilder<SigningCertificateRequirements> {
    // Lombok
  }

}
